[dOKR #591] Remove the need for Vault
infinum/default_rails_template pull request #129
Opened 2022-07-29 10:18 UTC by djordjelacmanovic

Task: [#591](https://app.productive.io/1-infinum/tasks/2752437)

#### Aim

During containerization efforts we have concluded that we will not be using Vault, so we want to make it an opt-in tool in the template.

2022-07-29 12:55 UTC, d4be4st requested changes

2022-07-29 12:55 UTC, d4be4st commented on template.rb
> -  config/application*.yml
We still need to ignore config/application.yml files.

1. You might push a credential while you are locally developing.
2. it will override environment variables on ECS.

My suggestion is to use a sample copying.
have `config/application.example.yml` which has all the required keys but values are empty.
in `bin/setup` do `mv config/application.example.yml config/application.yml`

we will also need this file for CI while testing

2022-08-29 07:25 UTC, uncoverd commented
@djordjelacmanovic what are our next steps here, do you need more reviews or do you just need to address Štef's comments?

2022-08-29 07:27 UTC, djordjelacmanovic commented
> @djordjelacmanovic what are our next steps here, do you need more reviews or do you just need to address Štef's comments?

That's it, unless anyone has additional comments

2022-08-30 07:34 UTC, d4be4st approved these changes

2022-08-30 07:43 UTC, merged