Add license_finder to template
infinum/default_rails_template pull request #138
Opened 2023-06-02 06:49 UTC by anamarijabalaban

Task: [#876](https://latest.productive.io/1-infinum/time/me/task/4779901?tour=time-week-layout)

#### Aim
Add license_finder to the template.

#### Solution
Added license_finder gem and prepared a list of restricted and permitted licenses. Also, license_finder is added to pre-commit hooks.

2023-06-02 14:30 UTC, vr4b4c commented on template.rb
> +run 'bundle exec license_finder permitted_licenses add "New BSD" "Simplified BSD" ' \
Where did all these licenses come from? How did you decide which ones are permitted?

2023-06-02 14:30 UTC, vr4b4c commented on template.rb
> +run 'bundle exec license_finder approvals add enumerations'
I wouldn't add this by default, only if the project actually depends on `enumerations`

2023-06-02 14:34 UTC, vr4b4c commented
Should we also run a license check in CI/CD pipeline?

2023-06-12 06:24 UTC, uncoverd requested changes

2023-06-12 06:24 UTC, uncoverd commented on template.rb
> +  run 'bundle exec license_finder approvals add @infinumrails/stylelint-config-scss @infinumrails/eslint-config-js'
I think this could be added as a post install warning (e.g. "you might need to add config-scss and eslint-config-js to the approved list manually with the following command"), I'm not sure it makes sense to always add it

2023-06-12 06:24 UTC, uncoverd commented on template.rb
> +    command: ['bundle', 'exec', 'license_finder']
How long does the command usually take on a bigger or smaller project?

2023-06-12 06:24 UTC, uncoverd commented on template.rb
> +run 'bundle exec license_finder ignored_groups add ci'
I think an audit would flag license misuse for these dependencies as well. How come you decided to ignore them?

2023-06-12 06:24 UTC, uncoverd commented on template.rb
> +run 'bundle exec license_finder permitted_licenses add "New BSD" "Simplified BSD" ' \
I think we have a pending OKR to go over the default list with Legal. @vlakre is this your list?

2023-06-12 07:03 UTC, vlakre commented on template.rb
> +run 'bundle exec license_finder permitted_licenses add "New BSD" "Simplified BSD" ' \
@uncoverd yep, I've compiled this list when adding this to Atlas. I went over the licenses from the gems we had, checked each one, and added it to the list. There might be other licenses that are ok to use but are not covered here.
If there's a chance to check these with Legal, by all means 💪

2023-06-25 19:52 UTC, anamarijabalaban commented on template.rb
> +run 'bundle exec license_finder permitted_licenses add "New BSD" "Simplified BSD" ' \
Yes, that is the list of permitted licenses that Kreso found on Atlas, but I think that I will need to expand this list because in the meantime I find some other non-restrictive licenses on some gems that are not present on Atlas. (on Loop and NLBL)

Also, I am planning to sit with our legal and check with them which group of licensees we need to avoid.

2023-06-25 20:01 UTC, anamarijabalaban commented on template.rb
> +run 'bundle exec license_finder ignored_groups add ci'
I wasn't 100% sure about this, so I talked with Kreso about this (since he was adding `lincense_finder` on Atlas and researching this topic before). In the end, I decided to ignore development, test and ci gems because they are not directly used in published app (staging and production), but I will definitely check this with our legal.

Also, an interesting thing is that `bundler-audit ` gem has a GPL-3.0 license which is a very strong copyleft license.

2023-06-30 09:29 UTC, anamarijabalaban commented on template.rb
> +    command: ['bundle', 'exec', 'license_finder']
I measure that locally on some projects that I have access:
loop - 23 sec
atlas (we have implemented some ignored groups and other rules) - 30 sec
lmt slovenia - 27sec
nlbl - 15 sec (no js dependencies)

2023-10-11 08:41 UTC, vlakre commented on template.rb
> +    command: ['bundle', 'exec', 'license_finder']
@uncoverd it will only be run when the Gemfile changes. So the long waiting time will only affect the commit where you add the new gem.

2023-10-11 11:37 UTC, uncoverd commented
@anamarijabalaban what are your thoughts on adding this on CI? Historically we used CI as the last line of defense as overcommit is not always installed. Afaik we'd need to add a command to the CI steps and introduce a `bin/license` file to run the command

2023-10-11 14:22 UTC, anamarijabalaban commented
@uncoverd I'm just preparing a separate PR that adds a GA workflow file for license scanning on the project that already has configured license_finder gem.

2023-10-31 07:48 UTC, nikajukic commented
@vr4b4c @uncoverd please do a final round of review before we merge this.

2023-11-02 06:39 UTC, uncoverd approved these changes

2023-11-10 11:37 UTC, vr4b4c approved these changes

2025-06-16 05:32 UTC, merged

2025-06-16 05:35 UTC, nikajukic commented
@anamarijabalaban these changes will need to be moved to https://github.com/infinum/rails-template, our new template repository