[Task #960] Introduce a feature flag system
infinum/default_rails_template pull request #149
Opened 2024-11-19 20:27 UTC by Benaaaaa

Task: [#960](https://app.productive.io/1-infinum/task/7909978)

#### Aim
We need to introduce a feature flag management system to the default Rails template. 

#### Solution
Introduce flipper to the project
Do not set ! on secrets regarding flipper cloud, as they are not necessary for Flipper to be working
Update the readme regarding Flipper

2024-11-20 13:35 UTC, uncoverd commented on README.md
> +This template uses Flipper for feature flag management. There are two ways for Flipper to function: **Cloud** and **Cloudless**. Cloudless will work out of the box, but if we want Flipper to be commu
Could you emphasize that the cloud version costs $$

2024-11-20 13:35 UTC, uncoverd commented on template.rb
> +    config.flipper.memoize = false # for some reason webhook requests are being called twice without this
Did you find any related issue in the repository?

2024-11-20 13:39 UTC, Benaaaaa commented on README.md
> +This template uses Flipper for feature flag management. There are two ways for Flipper to function: **Cloud** and **Cloudless**. Cloudless will work out of the box, but if we want Flipper to be commu
The cloud version is free though 🤔

2024-11-20 13:42 UTC, Benaaaaa commented on template.rb
> +    config.flipper.memoize = false # for some reason webhook requests are being called twice without this
There is a PR that is talking about it, and I tried digging into it more, but nowhere a real solution seemed to be presented: https://github.com/flippercloud/flipper/pull/523

2024-11-21 13:55 UTC, uncoverd commented on README.md
> +This template uses Flipper for feature flag management. There are two ways for Flipper to function: **Cloud** and **Cloudless**. Cloudless will work out of the box, but if we want Flipper to be commu
Oh my bad, I had a vague recollection of them only offering a paid cloud version 😓 Seems like it was introduced in August 2023, great 👍

2024-11-21 13:56 UTC, uncoverd approved these changes

2024-11-29 08:17 UTC, vr4b4c commented on README.md
> +This template uses Flipper for feature flag management. There are two ways for Flipper to function: **Cloud** and **Cloudless**. Cloudless will work out of the box, but if we want Flipper to be commu
Cloudless sounds a bit out-of-place. Self-hosted seems to be a conventional name for this use case, but I realize authors also use that naming, so it's fine.

2024-11-29 08:34 UTC, vr4b4c requested changes

2024-12-02 07:09 UTC, nikajukic commented on README.md
> +This template uses Flipper for feature flag management. There are two ways for Flipper to function: **Cloud** and **Cloudless**. Cloudless will work out of the box, but if we want Flipper to be commu
Maybe add "self-hosted" in brackets next to cloudless so it's clear?

2024-12-02 07:12 UTC, nikajukic commented on template.rb
> +    config.flipper.memoize = false # for some reason webhook requests are being called twice without this
Please add this link to the comment in the codebase.

2024-12-02 07:14 UTC, nikajukic commented on template.rb
> +   FLIPPER_CLOUD_SYNC_SECRET: ''
This is secrets.yml, so shouldn't this be `flipper_cloud_token` and `flipper_cloud_sync_secret`, downcased as other parameters as well?

2024-12-02 11:12 UTC, Benaaaaa commented on template.rb
> +   FLIPPER_CLOUD_SYNC_SECRET: ''
It seems a bit weird when reading it, but this is being added to the figaro file. Based on the documentation: 

> Using Environment Variables
Environment variables provide the easiest way to configure Flipper Cloud. Set a FLIPPER_CLOUD_TOKEN environment variable using [.dotenv](https://github.com/bkeepers/dotenv) or any other approach that works with environment variables, and Flipper will recognize it and handle the rest.
FLIPPER_CLOUD_TOKEN=your-cloud-token
FLIPPER_CLOUD_SYNC_SECRET=your-webhook-secret

By simply adding these two to the figaro file, figaro will load them as env variables upon startup. With such a setup, as long as the secrets are setup Flipper Cloud will work out of the box

2024-12-02 11:20 UTC, Benaaaaa commented on template.rb
> +# Flipper
It seems that the flipper setup should not be run at this point. Will move it downards.

2024-12-02 11:39 UTC, Benaaaaa commented on README.md
> +This template uses Flipper for feature flag management. There are two ways for Flipper to function: **Cloud** and **Cloudless**. Cloudless will work out of the box, but if we want Flipper to be commu
I was going with self-hosted first, but it seemed like if we only follow the setup process that it does not feel like we are hosting anything, but rather just using a cloudless approach. So the cloudless name seemed more appropriate for this. I will add the self-hosted next to cloudless for clarity purposes

2024-12-06 11:55 UTC, vr4b4c requested changes

2024-12-06 11:55 UTC, vr4b4c commented on template.rb
> +require 'tty-prompt'
No bueno, the template shouldn't depend on anything outside of the standard library. Currently, `rails new` fails if `tty-prompt` isn't installed beforehand
```
The template [https://raw.githubusercontent.com/infinum/default_rails_template/feature/960-introduce-a-feature-flag-management-system-to-the-default-rails-template/template.rb] could not be loaded. Error: cannot load such file -- tty-prompt
```

2024-12-06 11:55 UTC, vr4b4c commented on template.rb
> +   FLIPPER_CLOUD_SYNC_SECRET: ''
I don't think casing matters in practice, but I think we should keep it uniform. Since Figraro docs are using downcase and we followed it in other places, we should keep it consistent here as well, downcased.

2024-12-06 11:55 UTC, vr4b4c commented on template.rb
> +## Flipper setup for active record adapter
I don't think we need this comment if the logic is self-explanatory.

2024-12-20 11:43 UTC, Benaaaaa commented on template.rb
> +   FLIPPER_CLOUD_SYNC_SECRET: ''
I did introduce it downcased and it did not properly work downcased. Flipper cloud was not being loaded, it seems it is explicitly asking for upcased ENV variables

2024-12-20 11:45 UTC, Benaaaaa commented on template.rb
> +   FLIPPER_CLOUD_SYNC_SECRET: ''
E.g. our figaro variables are set downcased: 
![image](https://github.com/user-attachments/assets/a7c80604-d23c-46e6-a359-b3f02e62cec2)
And we need them to be upcased for Flipper to work

2024-12-20 11:54 UTC, Benaaaaa commented on template.rb
> +require 'tty-prompt'
😢

2025-01-14 09:30 UTC, Benaaaaa commented
@vr4b4c mostly just missing your review here, before this can be closed out

2025-01-14 09:48 UTC, vr4b4c commented
@Benaaaaa you have a conflict with the main branch

2025-01-14 10:15 UTC, vr4b4c approved these changes

2025-01-14 11:10 UTC, merged